/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as InformationRouteImport } from './routes/information'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as EducationRouteImport } from './routes/education'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/college': typeof CollegeRoute
  '/education': typeof EducationRoute
  '/experts': typeof ExpertsRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/information': typeof InformationRoute
  '/mission': typeof MissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/college': typeof CollegeRoute
  '/education': typeof EducationRoute
  '/experts': typeof ExpertsRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/information': typeof InformationRoute
  '/mission': typeof MissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/college': typeof CollegeRoute
  '/education': typeof EducationRoute
  '/experts': typeof ExpertsRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/information': typeof InformationRoute
  '/mission': typeof MissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/college'
    | '/education'
    | '/experts'
    | '/faculty'
    | '/faq'
    | '/information'
    | '/mission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/college'
    | '/education'
    | '/experts'
    | '/faculty'
    | '/faq'
    | '/information'
    | '/mission'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/college'
    | '/education'
    | '/experts'
    | '/faculty'
    | '/faq'
    | '/information'
    | '/mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CollegeRoute: typeof CollegeRoute
  EducationRoute: typeof EducationRoute
  ExpertsRoute: typeof ExpertsRoute
  FacultyRoute: typeof FacultyRoute
  FaqRoute: typeof FaqRoute
  InformationRoute: typeof InformationRoute
  MissionRoute: typeof MissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CollegeRoute: CollegeRoute,
  EducationRoute: EducationRoute,
  ExpertsRoute: ExpertsRoute,
  FacultyRoute: FacultyRoute,
  FaqRoute: FaqRoute,
  InformationRoute: InformationRoute,
  MissionRoute: MissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
